### ISSUE TITLE
Building heights for LCZ 7

### ISSUE THREAD

**Issue by jesusff** [FPS-URB-RCC/WRFcoordination#1]
https://github.com/FPS-URB-RCC/WRFcoordination/blob/c7f3201f515edac779f5c68c052c6bd18ea94d4b/URBPARM_LCZ.TBL#L598-L603

Lluís: Seems to me it should be 6?
Oscar: It should be 2. We have put 5 a while ago with Alberto because BEP only accepted levels of 5 m in the past.

**Comment by matthiasdemuzere** [comment]
I can confirm.

I m not sure what the original question is, but if you use [W2W](https://github.com/matthiasdemuzere/w2w) then these values are set by default.

In addition: the next release of WRF/WPS will allow you to use LCZs without having to use W2W. All of the required pre-processing will be done within WRF/WPS. It is for that reason I created [the hybrid Copernicus-Modis-LCZ land use map](https://zenodo.org/record/7670792).

Best,
Matthias

**Comment by jesusff** [comment]
Thank you for jumping in, @matthiasdemuzere 

> if you use W2W then these values are set by default.

Do you mean that W2W has hard-coded values for e.g. building heights, regardless of the setting in URBPARM_LCZ.TBL? We will likely keep using your tool in the FPS

> the next release of WRF/WPS will allow you to use LCZs without having to use W2W

Do you mean 4.5 (released a few days ago)? or is it intended for 4.5.1? 4.6? There seems to be already some capability to process your new data in v4.5

**Comment by andreazonato** [comment]
Hi all,

In version 4.5 you can find the LCZ map at 100m resolution. However, regarding the interpolation method to create point-by-point values has not been released yet, I'm working on it!
